### PR TITLE
CP-1675 Fix mock WSocket examples in readme

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
@stevenosborne-wf pointed out that the examples for mocking WSocket instances in the readme are incorrect.

## Solution
Fix them. **Documentation only change.**

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
