### PR TITLE
CP-2616 Release w_transport 2.9.4

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [Dont wait for WebSocket to close when the subscription is canceled](https://github.com/Workiva/w_transport/pull/227)

Requested by: evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.3...version-bump-w_transport-2-9-4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.3...2.9.4

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
QA Resource Approval: +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
