### PR TITLE
CP-1963 Upgrade to dart_style 0.2.4

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
We started hitting an RTE when running the dartfmt executable on this codebase. No idea what triggered it, but it seemed to be a bug in dart_style and not an issue with our code. The real issue though is that our `dartdoc` version range was preventing us from getting the latest `dart_style` - we were using 0.2.1 and the latest is 0.2.4.

## Solution
I've removed the `dartdoc` dev dependency for now. We get it transitively from dart_dev but dart_dev is behind on the version of `dartdoc` it supports, so that will need to be fixed first. By removing it, we can bump our minimum version of `dart_style` to 0.2.4 and this fixes the bug we were seeing above.

## Testing
- [ ] CI passes.

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
