### PR TITLE
CP-698 Add dartfmt check to CI build, w_transport.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- #33 

## Changes
- Updated `dartfmt.sh` script
- Added to CI build

## Areas of Regression
- n/a

## Testing
- CI build passes.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
 - CI passed, correct logging is displayed depending on the current state of the code's formatting
- [ ] Unit test created/updated
- [x] All unit tests pass

Merging into master.

**Pull request merged**
