### PR TITLE
WP-3986 Fix 3.0.3 changelog header

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Changes
Fix the wrong header for the 3.0.3 changelog.

**Docs change only.**

## Code Review
@Workiva/web-platform-pp

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
