### PR TITLE
CP-2426 Release w_transport 2.9.3

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [CP-2615 Prevent StateError when a request times out right after it is canceled](https://github.com/Workiva/w_transport/pull/215)

Requested by: charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.2...version-bump-w_transport-2-9-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.2...2.9.3

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by rmconsole-wf** [comment]
@rm-astro-wf, @edjackson+rmconsole-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/84523183/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
Manually verified that the travis steps were working locally, the dart runner used by travis CI is currently not working

```
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test --integration
  - pub run dart_dev coverage --integration --no-html
```

QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
