### PR TITLE
CP-1113 Add stream static methods to Http

### LINKED ISSUE #73: Add streamed static request dispatchers on `Http` class
Should be able to do:

```dart
Http.streamGet(...);
```

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Resolves #73 

## Changes
**Source:**
- Add streamed variants of the request methods on the `Http` class to make it easy to get a streamed response for simple requests.
- Bug fix: the browser implementation of streamed response was not constructing the byte stream correctly

**Tests:**
- Integration tests added

## Areas of Regression
- n/a

## Testing
- CI passes

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
