### PR TITLE
Release w_transport 3.0.5

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [WP-4462 add close_sinks and cancel_subscriptions lints to 3.x](https://github.com/Workiva/w_transport/pull/275)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.4...version-bump-w_transport-3-0-5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.4...3.0.5

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by toddbeckman-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
QA +1

- [x] Dev +1's only needed for Release ticket

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
