### PR TITLE
Release w_transport 3.0.2

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [CP-3328 Fix 'vm.dart' docs](https://github.com/Workiva/w_transport/pull/247)
* [CP-3434 Pass SockJS params through mock-aware proxy](https://github.com/Workiva/w_transport/pull/250)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.1...version-bump-w_transport-3-0-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.1...3.0.2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
