### PR TITLE
CP-1918 Update changelog for 2.5.0

### PR DESCRIPTION
**Pull request by evanweible-wf**
**Doc change only.**

---

@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
