### PR TITLE
CP-671 Add changelog, w_transport

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- #20 
- We need a changelog file, especially since it's displayed on pub.dartlang.org

- Added `CHANGELOG.md`

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@jayudey-wf 

---

I will keep this open until we're ready for the next release, at which point I'll finalize updates and get one last round of reviews. After that's merged and the release is cut, I'll reopen and repeat the process.

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf this has been updated, please re-review

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge, docs only change.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - doc change only, tests pass
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
