### PR TITLE
CP-1426 Release w_transport 2.4.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-1426

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1675  - Fix mock WSocket examples in readme  - https://github.com/Workiva/w_transport/pull/135

 CP-1705  - Hide dart:html.Client to avoid conflict with w_transport.Client  - https://github.com/Workiva/w_transport/pull/136

 CP-1709  - FormRequest: support fields with multiple values  - https://github.com/Workiva/w_transport/pull/137

 CP-1724  - Update changelog for 2.4.0  - https://github.com/Workiva/w_transport/pull/138

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.3.2...CP-1426_release_2.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.3.2...2.4.0

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
verified passing tests https://travis-ci.org/Workiva/w_transport/builds/127895533#L4520

currently there is a known issue with coverage https://github.com/dart-lang/coverage/issues/107

QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
