### PR TITLE
CP-1724 Update changelog for 2.4.0

### PR DESCRIPTION
**Pull request by evanweible-wf**
**Docs only change.**

---

@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@sebastianmalysa-wf 
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
QA +1 
- Docs only change

Merging into master.

**Comment by maxwellpeterson-wf** [comment]
@rmconsole-wf run_merge_script

**Pull request merged**
