### PR TITLE
WP-5326 Remove unused dependencies.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
There were two dev_dependencies that were unused.

## Solution
Remove them.

## Testing
- [ ] CI passes

## Code Review
@Workiva/web-platform-pp

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by evanweible-wf** [comment]
@Workiva/web-platform-pp ready for merge

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Minimum dependency bump only
- [x] Dev +1's
- [x] CI passes
- [x] Dependency scan clean

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
