### PR TITLE
CP-1250 Release w_transport 2.2.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1250

JIRA and PR's included in this release: 

 CP-1255  - FormRequest documentation typo  - https://github.com/Workiva/w_transport/pull/110

 CP-1337  - Add autoRetry config option for retrying timeouts  - https://github.com/Workiva/w_transport/pull/112

 CP-1330  - Add option for SockJS timeout  - https://github.com/Workiva/w_transport/pull/111

 CP-1343  - Fix formatting, changelog w_transport 2.2.0  - https://github.com/Workiva/w_transport/pull/113

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.1.0...CP-1250_release_2.2.0

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by ekweible** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
