### PR TITLE
CP-2849 Release w_transport 3.0.1

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [CP-3301 Disallow retry of canceled requests](https://github.com/Workiva/w_transport/pull/243)
* [[RED-659] Add Aviary.yaml](https://github.com/Workiva/w_transport/pull/225)
* [CP-2849 Update release date for 3.0.0](https://github.com/Workiva/w_transport/pull/237)
* [CP-2909 Pin Dart to 1.19.1 for Travis CI](https://github.com/Workiva/w_transport/pull/238)
* [CP-2942 Adding smithy.yaml](https://github.com/Workiva/w_transport/pull/239)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.0-rc.2...version-bump-w_transport-3-0-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.0-rc.2...3.0.1

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
