### PR TITLE
CP-2793 Release w_transport 3.0.0

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:

Requested by: @charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.4...version-bump-w_transport-3-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.4...3.0.0

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
No files changed? What is this magic?

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1, build failures are related to dart 1.20.*+ sdk version

 - ran `test` and `coverage` task locally and verified that they passed

Merging into master

**Pull request merged**
