### PR TITLE
CP-688 Use dart analyzer on test directory.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- #28 
- Dart analyzer tool already existed and was in the CI build, but it should also include the test/ directory.

## Changes
**Source:**
- n/a

**Tests:**
- Added the `noSuchMethod` implementation to all Mock classes to calm the compiler.

## Areas of Regression
- n/a

## Testing
- CI build passes.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, reviewed build logs to ensure that test directory was being analyzed

Merging into master

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Pull request merged**
