### PR TITLE
CP-1343 Fix formatting, changelog w_transport 2.2.0

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Changelog formatting was off.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by computmaxer** [comment]
+1
doc-only change

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
