### PR TITLE
CP-2425 Widen http_parser dependency range

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
The 1.x line of `http_parser` depended on an older version of the `crypto` package. This is causing some pain for downstream consumers (very slow or sometimes failed `pub get`s).

## Solution
Newer versions of the `http_parser` package no longer depend on `crypto` and don't have any breaking changes that would be an issue for `w_transport`. We can safely widen our dependency range to include both the 2.x and 3.x lines.

## Testing
- [ ] CI passes

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole-wf** [comment]
@evanweible-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/80987246/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by maxwellpeterson-wf** [comment]
+1 :shipit:

**Comment by dustinlessard-wf** [comment]
+1

**Comment by srinivasdhanwada-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by evanweible-wf** [comment]
@maxwellpeterson-wf @dustinlessard-wf @srinivasdhanwada-wf 

Added a changelog entry.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by srinivasdhanwada-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf @jayudey-wf @sebastianmalysa-wf @srinivasdhanwada-wf 

Changelog updated. All of the code changes are a result of a `dartfmt` run due to a new `dart_style` version.

**Comment by srinivasdhanwada-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
