### PR TITLE
CP-1255 FormRequest documentation typo

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- Typo in the readme and in the docstrings for `FormRequest` - `body` should be `fields` (thanks @christopherdaly-wf!)

## Changes
**Source:**
- Update readme and doc string

**Tests:**
- N/a

## Areas of Regression
- N/a

## Testing
- N/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
