### PR TITLE
CP-589 Release w_transport 1.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-589

JIRA and PR's included in this release: 

 CP-590  - HTTP (client & server) Implementation  - https://github.com/Workiva/w_transport/pull/2
 CP-593  - w_transport Licenses  - https://github.com/Workiva/w_transport/pull/3
 CP-596  - Run code through dartfmt.  - https://github.com/Workiva/w_transport/pull/4
 CP-600  - Redesign & refactor w_http API  - https://github.com/Workiva/w_transport/pull/5
 CP-604  - w_transport Update description and authors.  - https://github.com/Workiva/w_transport/pull/6
 CP-610  - w_transport Remove smithy  - https://github.com/Workiva/w_transport/pull/7
 CP-612  - w_transport1 Enable Travis-CI  - https://github.com/Workiva/w_transport/pull/9
 CP-614  - Refactor WResponse  - https://github.com/Workiva/w_transport/pull/8
 CP-618  - Make request cancellations cause failure (throw error)  - https://github.com/Workiva/w_transport/pull/10
 CP-623  - Change entry point to w_transport  - https://github.com/Workiva/w_transport/pull/11

Diff Between Last Tag and Proposed Release: N/A

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
