### PR TITLE
CP-2620 Enable Linter

### PR DESCRIPTION
**Pull request by evanweible-wf**
_Dependent on #217._

## Changes
- Enable the linter and most of the rules
- Note the rules that were omitted and the reason
- Make a bunch of changes to make the linter happy :)

## Testing
- [ ] CI passes
- [ ] Examples work as expected

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 2
* Watched keyword ```withCredentials``` in ```lib/src/http/finalized_request.dart``` line(s) ['43'] removed
* Watched keyword ```withCredentials``` in ```lib/src/http/finalized_request.dart``` line(s) ['39'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by rmconsole-wf** [comment]
@evanweible-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/84603398/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf rebased to get rid of the dependent commit

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf Jay found an issue with the file upload example - I was typing the mouse events as `Event` (from dart:html) instead of `SyntheticMouseEvent` from react.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
 - verified that examples are working as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by evanweible-wf** [comment]
@rmconsole-wf run_merge_script

**Pull request merged**
