### PR TITLE
WP-3505 Release w_transport 2.9.7

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [WP-3777 Complete `BaseRequest.done` on cancellation (BACKPATCH)](https://github.com/Workiva/w_transport/pull/256)

Requested by: @maxwellpeterson-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.6...version-bump-w_transport-2-9-7
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.6...2.9.7

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
