### PR TITLE
CP-2076 Increase duration tolerance for jitter tests

### PR DESCRIPTION
**Pull request by evanweible-wf**
_Fixes #186_ 

## Issue
Our CI builds were failing intermittently due to the waits in a couple of the jitter tests being too short.

## Solution
Adjust the timing of the two jitter tests to be more tolerant. We already have tests with jitter disabled that ensuring the retries are spread out as expected - the tests with jitter enabled just need to ensure that all attempts are being sent. There are additional unit tests covering the backoff (with jitter) functionality that test the utility methods directly.

## Testing
- [ ] CI passes.

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole-wf** [comment]
@evanweible-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/78625550/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
The diff is a bit weird because I moved one of the tests up.. sorry about that.

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
