### PR TITLE
CP-751 Add SDK constraint, w_transport

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- #39 

## Changes
- Add a Dart SDK constraint to pubspec.yaml.
- Also allows use to use the `^` syntax for dependencies
- Removed `dartium.sh` tool because it wasn't really useful.

## Areas of Regression
- n/a

## Testing
- `pub publish --dry-run` shows no warnings

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - tests pass, publish command does not result in any errors and example still works as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
