### PR TITLE
CP-1249 Update entry point library names.

### LINKED ISSUE #103: Main entry point library is named incorrectly
https://github.com/Workiva/w_transport/blob/master/lib/w_transport.dart#L90

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- Fix #103 

## Changes
**Source:**
- Two of the entry points have outdated library names, they've been fixed now.

**Tests:**
- n/a

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, library name change only

Merging into master

**Pull request merged**
