### PR TITLE
CP-3502 Release w_transport 2.9.6

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [CP-3486 Prevent XHR mutation after abort](https://github.com/Workiva/w_transport/pull/252)

Requested by: @jayudey-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.5...version-bump-w_transport-2-9-6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.5...2.9.6

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+!

**Comment by evanweible-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
Added a commit to copy the basic smithy config over from the 3.x line so that smithy actually runs successfully.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
