### PR TITLE
CP-1142 Release w_transport 2.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1142

JIRA and PR's included in this release: 

 CP-1147  - Target sockjs-dart-client release 0.3.0  - https://github.com/Workiva/w_transport/pull/83

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.0.0...CP-1142_release_2.0.1

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by ekweible** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by evanweible-wf** [comment]
+1

**Pull request merged**
