### PR TITLE
CP-1954 Release w_transport 2.7.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1954

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

======= w_transport 2.7.0 items =======

 CP-1974  - Restore & deprecate autoRetry.backOff.duration for backwards compatibility  - https://github.com/Workiva/w_transport/pull/163

 CP-1975  - Update changelog for 2.7.0  - https://github.com/Workiva/w_transport/pull/164

 CP-1966  - Handle request with no encoding and no charset  - https://github.com/Workiva/w_transport/pull/161

 CP-1605  - Introduce jitter to exponential backoff  - https://github.com/Workiva/w_transport/pull/158

 CP-1963  - Upgrade to dart_style 0.2.4  - https://github.com/Workiva/w_transport/pull/160

======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.6.0...CP-1954_release_2.7.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.6.0...2.7.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
