### PR TITLE
CP-1160 Remove old mock file.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- An old mock file remains in the source code (possibly due to a bad merge conflict resolution)

## Changes
**Source:**
- Remove the old mock file

**Tests:**
- n/a

## Areas of Regression
- n/a

## Testing
- CI passes

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
