### PR TITLE
WP-4672 Dart dev compiler compatibility

### LINKED ISSUE #277: DDC incompatibility
This small snipetts fail on ddc:
```dart
import 'dart:async';
import 'package:w_transport/browser.dart' as wt;
import 'package:w_transport/w_transport.dart' as wt;


Future main() async {
  wt.configureWTransportForBrowser();
  wt.HttpClient client = new wt.HttpClient();
  (await client.newFormRequest()
    ..uri = Uri.parse('/'))
        .post();
}
```

The problem is the `_send` method in `CommonRequest` class is returning with `Future<BaseResponse>`  and the inherited methods from the `RequestDispatchers` class is overrided like:
```dart
  @override
  Future<Response> post({dynamic body, Map<String, String> headers, Uri uri}) =>
      _send('POST', body: body, headers: headers, uri: uri);
```
The problem is `Future<BaseRespone>` is not subtype of `Future<Respone>`.

### PR DESCRIPTION
**Pull request by evanweible-wf**
Fixes #277.

## Issue

There were a few typing issues that were preventing compatibility with the dart dev compiler.

## Solution

Fix them!

## Testing
- [ ] CI passes
- [ ] Unit tests pass when compiled via the dart dev compiler:
  - Checkout this branch locally
  - `pub get`
  - in one terminal: `pub serve test --web-compiler=dartdevc`
  - in a second terminal: `pub run test -p chrome --pub-serve=8080 test/unit/platform_independent_unit_test.dart`

## Code Review

@Workiva/web-platform-pp 
fyi @valakis

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by sebastianmalysa-wf** [comment]
+10 - Pulled down branch and followed testing instructions. All tests pass.

**Comment by evanweible-wf** [comment]
QA +1
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit tests created/updated 
- [x] All unit tests pass

Merging into master.
@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
