### PR TITLE
CP-2848 3.0.0

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Description
The 3.0.0-wip branch is ready to be merged into master.

## Commits -> PRs
- d263f5a, ae48789, cb1049a: #198 
- 3b38838: #197 
- 080370e: #209 
- 16da947:  #212 
- 4051651: #217 
- abf4276: #219 
- 400a87f: #220 
- a600cbe, 85ae35f: #221 
- 213b273: #222 
- 62e334c: #224 
- db4a6f4: #210 
- 6354928: #231 
- fd15970: #232 
- c819818, c22266b: #233 

The only commits not listed above are merge commits and release PR commits.

## Testing
- [ ] CI passes (will have to do this manually)

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 11
* Watched keyword ```x-xsrf-token``` in ```README.md``` line(s) ['507', '586'] removed
* Watched keyword ```x-xsrf-token``` in ```docs/guides/HttpIntercepting.md``` line(s) ['132'] added
* Watched keyword ```withCredentials``` in ```lib/src/http/finalized_request.dart``` line(s) ['45'] removed
* Watched keyword ```withCredentials``` in ```lib/src/http/common/http_client.dart``` line(s) ['48', '98', '106-107'] added
* Watched keyword ```withCredentials``` in ```lib/src/http/http.dart``` line(s) ['30', '34', '44', '48', '58', '62', '72', '76', '88', '93', '105', '110', '122', '127', '139', '144', '155', '159', '170', '174', '185', '189', '200', '204', '216', '221', '233', '238', '250', '255', '268', '273', '280'] added
* Watched keyword ```withCredentials``` in ```lib/src/http/finalized_request.dart``` line(s) ['39'] added
* Watched keyword ```x-xsrf-token``` in ```docs/guides/HttpClient.md``` line(s) ['18'] added
* Watched keyword ```withCredentials``` in ```lib/src/http/mock/request_mixin.dart``` line(s) ['81'] added
* Watched keyword ```withCredentials``` in ```lib/src/http/common/client.dart``` line(s) ['49', '96', '104-105'] removed
* Watched keyword ```withCredentials``` in ```lib/src/http/http.dart``` line(s) ['29-30', '38-39', '47-48', '56-57', '66', '68', '77', '79', '88', '90', '99', '101', '110-111', '120-121', '130-131', '140-141', '150', '152', '161', '163', '172', '174', '184', '186', '190'] removed
* Watched keyword ```withCredentials``` in ```lib/src/http/http_client.dart``` line(s) ['23'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by maxwellpeterson-wf** [comment]
+1
- All commits accounted for in other PRs

**Comment by maxwellpeterson-wf** [comment]
+1 security
- Necessary security +1s completed in intermediate PRs

**Comment by trentgrover-wf** [comment]
looks like there are actual test failures in those Travis CI runs....

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge (assuming tests pass locally)

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that examples were working as expected
 - ran `test` and `coverage` task were passing as expected locally (failure due to travis)
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
