### PR TITLE
CP-1884 Fix Coverage, w_transport

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Coverage should be working with the latest Dart SDK release (1.17.0) and at least `coverage` 0.7.4. Additionally, codecov.io made a change that now requires configuration to be set in a `codecov.yml` file instead of through their UI. This is why code coverage comments and the CI status check have not been appearing on recent PRs.

## Solution
Upgrade to `coverage ^0.7.4` and add a `codecov.yml`.

## Testing
- [ ] CI passes (in particular, the coverage step)
- [ ] Coverage is reported to codecov.io
- [ ] Coverage comment is added to this PR
- [ ] Coverage CI check shows up and passes

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
I was expecting the coverage comment and CI check to work immediately, but coverage was reported successfully already (https://codecov.io/gh/Workiva/w_transport/branch/coverage) and I'm not seeing anything. It may have to be merged to master first...

**Comment by evanweible-wf** [comment]
@jayudey-wf let's go ahead and try merging this, then I'll rebase the other open PRs and see if that triggers the coverage hooks.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that coverage was being reported to codecov
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
