### PR TITLE
CP-1364 Release w_transport 2.3.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1364

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1382  - Workaround for dart2js bug when request is canceled.  - https://github.com/Workiva/w_transport/pull/122

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.3.0...CP-1364_release_2.3.1

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
