### PR TITLE
do not merge, testing

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
test post please ignore

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole-wf** [comment]
@maxwellpeterson-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/82479934/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by semveraudit-wf** [comment]
test post

**Comment by semveraudit-wf** [comment]
```diff
                N
o
 
a
u
d
i
t
 
f
o
r
 
b
a
s
e
 
b
3
7
8
c
e
5
1
6
7
e
5
0
4
d
9
a
f
6
f
3
d
8
e
2
8
5
6
8
a
4
4
6
7
c
b
8
7
4
e
            ```

**Comment by rmconsole-wf** [comment]
@maxwellpeterson-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/82479934/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by semveraudit-wf** [comment]
```diff
  @@ line 13: package:semver_audit/src/example.dart @@
- enum ExampleEnum {one, two}
+ enum ExampleEnum {one, two, three}

@@ line 67: package:semver_audit/src/example.dart @@
- class FactoryClass {}
+ class FactoryClass implements AbstractClass {}

@@ line 39: package:semver_audit/src/example.dart @
+ String get exampleGetterOnly;

@@ line 55: package:semver_audit/src/example.dart @@
- void exampleMethod(String arg, int arg2);
+ void exampleMethod(String arg, int arg2, {String optional});
```

**Comment by semveraudit-wf** [comment]
### Public API Changes
```diff
@@ line 1: package:semver_audit/src/example.dart @
+ aNewVariable

@@ line 15: package:semver_audit/src/example.dart @@
- enum ExampleEnum {one, two, three}
+ enum ExampleEnum {one, two}

@@ line 69: package:semver_audit/src/example.dart @@
- class FactoryClass implements AbstractClass {}
+ class FactoryClass {}

@@ line 39: package:semver_audit/src/example.dart @
- String get exampleGetterOnly;

@@ line 57: package:semver_audit/src/example.dart @@
- void exampleMethod(String arg, int arg2, {String optional});
+ void exampleMethod(String arg, int arg2);
```

**Pull request closed without merging**
