### PR TITLE
CP-2098 Release w_transport 2.9.1

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-2098

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

======= w_transport 2.9.1 items =======

 CP-2286  - Ensure WSocket always reaches "done" state.  - https://github.com/Workiva/w_transport/pull/202

======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.0...CP-2098_release_2.9.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.0...2.9.1

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
