### PR TITLE
CP-2849 Update release date for 3.0.0

### PR DESCRIPTION
**Pull request by evanweible-wf**
**Docs only change.**

@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge (docs only)

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Comment by jayudey-wf** [comment]
+1

**Pull request merged**
