### PR TITLE
FEA-1543: Run CI on newer Dart SDK versions

### PR DESCRIPTION
**Pull request by evanweible-wf**
We're currently only running CI on Dart 2.13.4 because we were blocked from newer versions by our transitive dependency on `analyzer`. We are now able to resolve to analyzer v1, so we can run on newer Darts.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by todbachman-wf — APPROVED** [review]

**Comment by evanweible-wf** [comment]
QA +1
- [x] CI is once again passing (which includes integration tests that run against the test servers)
- [x] Ran the examples locally and verified that they work with the test server code moved around

**Comment by evanweible-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
