### PR TITLE
CP-754 Update tests to run with content shell instead of dartium

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- When using the test script if you have multiple versions of dartium installed you will get failed results when running the integration tests.

## Changes
**Source:**
- Updated test runner to use content shell

**Tests:**
- n/a

## Areas of Regression
- the test.sh script

## Testing
- run the test.sh script to ensure that it's still working

## Code Review
@trentgrover-wf
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready to merge

**Comment by evanweible-wf** [comment]
+10
- Ran a git clean and then ran `./tool/test.sh` and all tests pass.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - Evan ran script and verified passing results
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
