### PR TITLE
CP-627 Release w_transport 1.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-627

JIRA and PR's included in this release: 

 CP-631  - Allow request data to be set to null  - https://github.com/Workiva/w_transport/pull/14
 CP-640  - Add pub badge w_transport  - https://github.com/Workiva/w_transport/pull/13
 CP-641  - Listen for Request Cancellation in Client  - https://github.com/Workiva/w_transport/pull/15
 CP-658  - Report coverage to codecov.io  - https://github.com/Workiva/w_transport/pull/17
 CP-660  - Use dartanalyzer  - https://github.com/Workiva/w_transport/pull/22
 CP-661  - Reorganize class elements  - https://github.com/Workiva/w_transport/pull/24
 CP-663  - Use package: imports for src/ files, w_transport  - https://github.com/Workiva/w_transport/pull/25
 CP-664  - Validate data type when sending, not before  - https://github.com/Workiva/w_transport/pull/18
 CP-685  - cancelled to canceled, w_transport  - https://github.com/Workiva/w_transport/pull/29
 CP-688  - Use dart analyzer on test directory.  - https://github.com/Workiva/w_transport/pull/30
 CP-698  - Add dartfmt check to CI build, w_transport.  - https://github.com/Workiva/w_transport/pull/34
 CP-702  - Verify config is set before constructing WHttp  - https://github.com/Workiva/w_transport/pull/36
 CP-714  - Temporarily remove code coverage dependencies, w_transport  - https://github.com/Workiva/w_transport/pull/37
 CP-671  - Add changelog, w_transport  - https://github.com/Workiva/w_transport/pull/26

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/1.0.0...CP-627_release_1.0.1

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1
Ready for publish.

**Pull request merged**
