### PR TITLE
CP-1165 Dart formatter updates for w_transport, dart_style 0.2.1

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- `dart_style` 0.2.1 is out with improved formatting

## Changes
- Apply newest formatting

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@evanweible-wf should update pubspec to make 0.2.1 minimum

**Comment by evanweible-wf** [comment]
@maxwellpeterson-wf done

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
