### PR TITLE
CP-884 Ensure license is applied to all source files, w_transport

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Some new files are missing the license. Additionally, the license was previously added to dart files with the `/**` comments, but `//` is preferred.

## Changes
Licenses everywhere!

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1 based on this compare:
https://github.com/Workiva/w_transport/compare/dev...license
but looks like dependent PR has CI failures to deal with

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf @jayudey-wf rebased on latest master.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@trentgrover-wf

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - change includes only updates to comments
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
