### PR TITLE
Re-add stack_trace dependency

### PR DESCRIPTION
**Pull request by evanweible-wf**
Re-add a stack_trace dependency that was erroneously removed.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by aaronlademann-wf** [comment]
+1

**Comment by todbachman-wf** [comment]
+10. Confirmed CI passed.

**Comment by evanweible-wf** [comment]
QA +1
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit tests created/updated 
- [x] All unit tests pass

Merging into master.

**Pull request merged**
