### PR TITLE
CP-1725 Release w_transport 2.5.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-1725

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

======= w_transport 2.5.0 items =======

 CP-1918  - Update changelog for 2.5.0  - https://github.com/Workiva/w_transport/pull/149

 CP-1880  - WSocket: StreamSubscription onError, onDone aren't honored  - https://github.com/Workiva/w_transport/pull/142

 CP-1884  - Fix Coverage, w_transport  - https://github.com/Workiva/w_transport/pull/146

 CP-1862  - Upgrade to sockjs-dart-client 0.3.1  - https://github.com/Workiva/w_transport/pull/145
======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.4.0...CP-1725_release_2.5.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.4.0...2.5.0

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
