### PR TITLE
CP-3299 Release w_transport 2.9.5

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [CP-3323 BACKPATCH Disallow retry of canceled requests](https://github.com/Workiva/w_transport/pull/244)

Requested by: @jayudey-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.4...version-bump-w_transport-2-9-5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.4...2.9.5

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you (smithy failure expected)

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

 verified dependencies

**Pull request merged**
