### PR TITLE
CP-1975 Update changelog for 2.7.0

### PR DESCRIPTION
**Pull request by evanweible-wf**
**Docs change only.**

Updates the changelog for the 2.7.0 release.

@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
